controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
   path: /
   controller: App\Controller\BienController::index

dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index